### ISSUE TITLE
可以更改成底部6个按钮吗

### ISSUE THREAD

**Issue by xiaobeifeng** [leichunfeng/WXTabBarController#13]

**Comment by leichunfeng** [comment]
因为是继承的系统的 `UITabBarController` ，所以行为上是跟系统的一致，最多同时支持五个：

`The tab bar has limited space for displaying your custom items. If you add six or more custom view controllers to a tab bar controller, the tab bar controller displays only the first four items plus the standard More item on the tab bar. Tapping the More item brings up a standard interface for selecting the remaining items.`
