### ISSUE TITLE
运行demo 有个bug [__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]

### ISSUE THREAD

**Issue by hongjinlin** [leichunfeng/WXTabBarController#20]
运行demo 有个bug [__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]
xcode 8.3.2

**Comment by hongjinlin** [comment]
请问下大神怎么破？

**Comment by hongjinlin** [comment]
这项目有个坑，controller的view 是 通过addSubview 添加到 scrollView,所以controller的 viewWillAppear等方法是不会执行的

**Comment by leichunfeng** [comment]
有添加为子控制器，但是却没有触发 viewWillAppear 等方法，还没有找出原因
