### ISSUE TITLE
能否提供调用说明

### ISSUE THREAD

**Issue by sparkxxf** [leichunfeng/WXTabBarController#3]
你好，很棒的库，只是能否提供调用说明？新手不知道应该怎么调用，直接 pod 到库里就可以了么？还是说要调用某个 func
谢谢

**Comment by leichunfeng** [comment]
目前还没有提供 podspec ，所以还不能通过 Pod 来引入，因为我觉得还不够成熟，等足够成熟了我才会提供 podspec 。所以如果你现在想试用的话，直接把 Soure 目录下的两个文件添加到你的工程即可，而如何使用的话可以参考 AppDelegate 里面的做法。

**Comment by skyline75489** [comment]
弱弱地问一句，这是什么语法：

``` objecitive-c

UIViewController *vc1 = ({
    UIViewController *v = [[UIViewController alloc] init];    
    v;
});
```

**Comment by leichunfeng** [comment]
@skyline75489 请参考这个 issue [#1](https://github.com/leichunfeng/WXTabBarController/issues/1)

**Comment by sparkxxf** [comment]
@leichunfeng 好的，感谢。请问不太成熟具体是指哪方面，性能方面么

**Comment by leichunfeng** [comment]
我个人觉得还有以下几个点需要去完善吧：
- 目前所有 Tab 页是共用一个导航栏的，需要考虑兼容每个 Tab 页都有自己独立导航栏的情况，至少要能够自然地切换标题吧；
- 目前所有 Tab 页的 view 是一次性全部加载的，需要考虑第一次只加载第一个 Tab 页的 view ，然后以懒加载的方式加载其他 Tab 页的 view 。否则，目前这种一次性全部加载的方式可能会对应用的启动速度造成一些影响，至于具体程度我还没有评估过；
- 另外，就是与 cell 的滑动删除手势冲突的问题，尽管我不认为 cell 的滑动删除手势是一种非常好的、不可或缺的交互，但是如果能够兼容的话就最好不过了。

**Comment by sparkxxf** [comment]
之前没想到，你说的3点问题确实很全面，尤其是第一种情况确实很常见，而第二种情况也确实会造成一些性能影响。至于第三种，如你所说，有了更好，没有也没啥了。
